/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import javax.swing.*;
import java.awt.*;
/**
 *
 * @author syafiq
 */
public class LoadingForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoadingForm.class.getName());
     private javax.swing.JProgressBar progressBar;
      private javax.swing.JLabel logoLabel;
    /**
     * Creates new form LoadingForm
     */
    public LoadingForm() {
        initComponents();
       
        setTitle("Loading...");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(600, 600);
        setLocationRelativeTo(null); // biar form di tengah layar
        setLayout(new BorderLayout());

           // 🚀 pakai panel custom sebagai background
      Image bg = new ImageIcon(getClass().getResource("/images/ijmnenlogo.jpg")).getImage();
        JPanel centerPanel = new helper.BackgroundPanel(bg, false, 0);  
centerPanel.setLayout(new GridBagLayout()); // biar bisa taruh komponen di tengah

        // Progress bar di bawah
        progressBar = new JProgressBar(0, 100);
        progressBar.setStringPainted(true); // biar ada persen
        progressBar.setPreferredSize(new Dimension(600, 30));

        // Tambahkan ke frame
        add(centerPanel, BorderLayout.CENTER);
        add(progressBar, BorderLayout.SOUTH);
    }

     public void startLoading() {
        new Thread(() -> {
            for (int i = 0; i <= 100; i++) {
                final int value = i;
                SwingUtilities.invokeLater(() -> progressBar.setValue(value));
                try {
                    Thread.sleep(10); // delay simulasi loading
                } catch (InterruptedException ignored) {}
            }
            // setelah selesai, tampilkan form lain atau tutup
            SwingUtilities.invokeLater(() -> {
                dispose();
                new AuthForm().setVisible(true);
             //   JOptionPane.showMessageDialog(null, "Loading selesai!");
            });
        }).start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 637, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
